/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as CupsRouteImport } from './routes/cups'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiPublicQuoteRouteImport } from './routes/api/public/quote'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const CupsRoute = CupsRouteImport.update({
  id: '/cups',
  path: '/cups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuoteRoute = ApiPublicQuoteRouteImport.update({
  id: '/api/public/quote',
  path: '/api/public/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cups': typeof CupsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/quote': typeof ApiPublicQuoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cups': typeof CupsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/quote': typeof ApiPublicQuoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cups': typeof CupsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/quote': typeof ApiPublicQuoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cups'
    | '/thank-you'
    | '/admin/login'
    | '/admin/'
    | '/api/public/contact'
    | '/api/public/quote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cups'
    | '/thank-you'
    | '/admin/login'
    | '/admin'
    | '/api/public/contact'
    | '/api/public/quote'
  id:
    | '__root__'
    | '/'
    | '/cups'
    | '/thank-you'
    | '/admin/login'
    | '/admin/'
    | '/api/public/contact'
    | '/api/public/quote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CupsRoute: typeof CupsRoute
  ThankYouRoute: typeof ThankYouRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicQuoteRoute: typeof ApiPublicQuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cups': {
      id: '/cups'
      path: '/cups'
      fullPath: '/cups'
      preLoaderRoute: typeof CupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quote': {
      id: '/api/public/quote'
      path: '/api/public/quote'
      fullPath: '/api/public/quote'
      preLoaderRoute: typeof ApiPublicQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CupsRoute: CupsRoute,
  ThankYouRoute: ThankYouRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicQuoteRoute: ApiPublicQuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
